# Generated by Django 2.1.1 on 2018-09-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180916_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_Gate',
            new_name='created_date',
        ),
    ]
