# Generated by Django 2.1.1 on 2018-09-16 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
